Repository ebokyung/eggplant-market-react, pull requests merged in 2023-12, with the labels that each got.

#81 fix : 댓글 입력 버그 수정
  src/pages/Post/components/CommentInputSkeleton.jsx
  src/pages/Post/routes/PostDetail.jsx
Labels: 🐞 버그

#79 Feat : 무한 스크롤
  src/components/Element/Input/InputImg.jsx
  src/components/Element/Post/Post.jsx
  src/components/Element/Post/Post.scss
  src/hooks/scroll.js
  src/libs/api/fetchClosure.js
  src/pages/ChatRoom/routes/ChatRoom.jsx
  src/pages/Follow/routes/Follow.jsx
  src/pages/Home/routes/Home.jsx
  src/pages/Posting/components/ImageArea.jsx
  src/pages/Product/components/InputProductImage.jsx
  src/pages/Profile/routes/UserProfile.jsx
  src/utils/scroll.js
Labels: 🛠️ 기능개발

#86 refactor : 아이콘 사이즈 고정
  package-lock.json
  package.json
  src/components/Element/Header/Header.jsx
  src/components/Element/Header/Header.scss
  src/components/Element/Post/Post.jsx
  src/components/Element/Post/Post.scss
  src/libs/dummy/index.js
Labels: ⚙️ 개발환경, ♻️ 리팩토링

#88 fix: useLazyLoad options 제거
  src/hooks/useLazyLoad.jsx
Labels: 🐞 버그

#92 Feat/modal
  .eslintrc
  src/components/Element/Modal/Alert.jsx
  src/components/Element/Modal/Modal.jsx
  src/pages/Profile/components/SkeletonProfile.jsx
  src/pages/SignUp/routes/SignUp.jsx
Labels: ⚙️ 개발환경, 🛠️ 기능개발

#90 fix : '게시' 사이즈 수정
  src/pages/Post/style/CommentInput.scss
Labels: 🎨 디자인

#91 add : skipnavigation 부착 + 수정페이지 진입 버그 해결
  src/components/Element/Header/Header.jsx
  src/components/Element/Navbar/Navbar.jsx
  src/components/Element/SkipNav/SkipNav.jsx
  src/components/Element/SkipNav/SkipNav.scss
  src/pages/Home/components/HomeWithPost.jsx
  src/pages/Home/components/HomeWithoutPost.jsx
  src/pages/Home/routes/Home.jsx
  src/pages/Post/components/CommentInput.jsx
  src/pages/Post/routes/PostDetail.jsx
  src/pages/Profile/components/PostSection.jsx
  src/pages/Profile/routes/UserProfile.jsx
  src/utils/imageUrlProcess.js
Labels: 🐞 버그, 🛠️ 기능개발
