Repository ebokyung/eggplant-market-react, pull requests merged in 2023-11, with the labels that each got.

#66 refactor : 채팅목록-채팅방 더미 데이터 수정 및 roomId에 맞는 데이터 렌더링
  src/libs/dummy/chatRoom.js
  src/pages/ChatList/components/ChatListItem.jsx
  src/pages/ChatRoom/routes/ChatRoom.jsx
Labels: ♻️ 리팩토링

#67 design : 상품 등록/수정 페이지 스켈레톤
  .eslintrc
  package-lock.json
  package.json
  src/components/Element/Header/Header.jsx
  src/components/Skeleton/Fieldset.jsx
  src/pages/Product/components/ProductForm.jsx
  src/pages/Product/routes/Product.jsx
  src/pages/Product/styles/Product.scss
Labels: 🎨 디자인

#72 add : 더보기 버튼에 모달창 연결
  package-lock.json
  package.json
  src/App.js
  src/components/Element/Buttons/ButtonOption.jsx
  src/components/Element/Buttons/ButtonOptionComment.jsx
  src/components/Element/Buttons/ButtonOptionPost.jsx
  src/components/Element/Buttons/api/index.js
  src/components/Element/Buttons/index.js
  src/components/Element/Modal/Alert.jsx
  src/components/Element/Modal/Alert.scss
  src/components/Element/Modal/Modal.jsx
  src/components/Element/Modal/Modal.scss
  src/components/Element/Post/Post.jsx
  src/pages/Post/components/Comment.jsx
  src/pages/Posting/components/ImageItem.jsx
  src/pages/Product/components/InputProductImage.jsx
  src/pages/Product/components/ProductForm.jsx
  src/pages/Profile/api/index.js
  src/pages/Profile/components/ProductSectionElement/ProductItem.jsx
  src/recoil/modal/atoms.js
  src/routes/index.js
Labels: 🎨 디자인, 🛠️ 기능개발

#73 design : 프로필 수정 페이지 스켈레톤
  src/pages/EditProfile/routes/EditProfile.jsx
Labels: 🎨 디자인

#68 design : search skeleton (pr 작성중)
  src/pages/Posting/components/ImageItem.jsx
  src/pages/Search/routes/Search.jsx
  src/pages/Search/style/Search.scss
Labels: 🎨 디자인

#69 design : posting skeleton (PR작성중)
  src/pages/Posting/components/ImageArea.jsx
  src/pages/Posting/components/ImageItem.jsx
  src/pages/Posting/routes/Posting.jsx
  src/pages/Posting/style/Posting.scss
  src/pages/Posting/style/TextArea.scss
Labels: 🎨 디자인

#74 design : 사용자프로필 페이지 스켈레톤
  src/pages/Product/components/InputProductImage.jsx
  src/pages/Profile/routes/UserProfile.jsx
  src/pages/Profile/styles/ProductSection.scss
Labels: 🎨 디자인

#80 refactor : lazy import & remove index.js
  src/pages/ChatList/index.js
  src/pages/ChatList/routes/ChatList.jsx
  src/pages/ChatRoom/index.js
  src/pages/ChatRoom/routes/ChatRoom.jsx
  src/pages/EditProfile/index.js
  src/pages/EditProfile/routes/EditProfile.jsx
  src/pages/Error/Error.jsx
  src/pages/Follow/index.js
  src/pages/Follow/routes/Follow.jsx
  src/pages/Home/components/HomeWithPost.jsx
  src/pages/Home/components/HomeWithoutPost.jsx
  src/pages/Home/components/index.js
  src/pages/Home/index.js
  src/pages/Home/routes/Home.jsx
  src/pages/Login/index.js
  src/pages/Login/routes/Login.jsx
  src/pages/Login/routes/LoginEmail.jsx
  src/pages/Post/index.js
  src/pages/Post/routes/PostDetail.jsx
  src/pages/Posting/index.js
  src/pages/Posting/routes/Posting.jsx
  src/pages/Product/index.js
  src/pages/Product/routes/Product.jsx
  src/pages/Profile/index.js
  src/pages/Profile/routes/UserProfile.jsx
  src/pages/Search/components/SearchItem.jsx
  src/pages/Search/index.js
  src/pages/Search/routes/Search.jsx
  src/pages/SignUp/index.js
  src/pages/SignUp/routes/SignUp.jsx
  src/pages/Splash/Splash.jsx
  src/pages/index.js
  src/routes/index.js
Labels: 🛠️ 기능개발
