Repository ebokyung/eggplant-market-react, pull requests merged in 2023-09, with the labels that each got.

#20 홈화면 마크업, 디자인
  .eslintrc
  src/components/Element/Header/Header.scss
  src/components/Element/Post/Post.jsx
  src/components/Element/Post/Post.scss
  src/components/Element/Post/index.js
  src/components/Element/User/style/User.scss
  src/components/Element/index.js
  src/libs/dummy/posts.js
  src/pages/Home/components/HomeWithPost.jsx
  src/pages/Home/components/HomeWithoutPost.jsx
  src/pages/Home/components/index.js
  src/pages/Home/index.js
  src/pages/Home/routes/Home.jsx
  src/pages/Home/style/Home.scss
  src/routes/index.js
Labels: 🎨 디자인

#31 design : 검색 페이지 & refactor : import/export 관련 수정
  src/components/Element/Buttons/style/MainButton.scss
  src/components/Element/Buttons/style/OtherButton.scss
  src/components/Element/Header/Header.jsx
  src/components/Element/Navbar/Navbar.scss
  src/components/Element/User/ProfileImg.jsx
  src/components/Element/User/User.jsx
  src/components/Element/User/UserInfo.jsx
  src/components/Element/User/index.js
  src/components/Element/User/style/UserInfo.scss
  src/libs/dummy/chatListData.js
  src/libs/dummy/chatRoom.js
  src/libs/dummy/index.js
  src/libs/dummy/posts.js
  src/libs/dummy/product.js
  src/libs/dummy/search.js
  src/pages/ChatList/routes/ChatList.jsx
  src/pages/ChatRoom/components/ChatBubble.jsx
  src/pages/Home/components/HomeWithoutPost.jsx
  src/pages/Search/Components/SearchItem.jsx
  src/pages/Search/Components/SearchItem.scss
  src/pages/Search/index.js
  src/pages/Search/routes/Search.jsx
  src/pages/Search/style/Search.scss
  src/routes/index.js
Labels: 🎨 디자인, ♻️ 리팩토링

#34 게시글 컴포넌트 수정
  src/components/Element/Post/ButtonLike.jsx
  src/components/Element/Post/Post.jsx
Labels: 🐞 버그, ♻️ 리팩토링

#45 refactor : input, errormsg 컴포넌트 마크업 및 스타일 병합
  src/components/Element/Input/ErrorMsg.jsx
  src/components/Element/Input/ErrorMsg.scss
  src/components/Element/Input/Input.jsx
  src/components/Element/Input/Input.scss
  src/components/Element/Input/index.js
Labels: ♻️ 리팩토링

#39 design : 팔로잉 팔로워 페이지 마크업 및 eslint 설정 추가
  .eslintrc
  src/components/Element/Follow/Follow.scss
  src/components/Element/Follow/FollowItem.jsx
  src/components/Element/User/User.jsx
  src/pages/Follow/components/FollowButton.jsx
  src/pages/Follow/components/FollowItem.jsx
  src/pages/Follow/components/FollowList.jsx
  src/pages/Follow/index.js
  src/pages/Follow/routes/Follow.jsx
  src/pages/Follow/style/Follow.scss
  src/pages/Search/components/SearchItem.jsx
  src/pages/Search/components/SearchItem.scss
  src/routes/index.js
  src/styles/scss/profile_follow.scss
Labels: ⚙️ 개발환경, 🎨 디자인

#50 design & add : 이메일로 로그인
  src/pages/Login/Login.scss
  src/pages/Login/components/LoginForm.jsx
  src/pages/Login/index.js
  src/pages/Login/routes/Login.jsx
  src/pages/Login/routes/LoginEmail.jsx
  src/pages/Login/styles/Login.scss
  src/pages/Login/styles/LoginEmail.scss
  src/pages/index.js
  src/routes/index.js
Labels: 🎨 디자인, 🛠️ 기능개발, ♻️ 리팩토링
