Repository ebokyung/eggplant-market-react, pull requests merged in 2023-10, with the labels that each got.

#49 design & add : 상품 업로드/수정 페이지
  src/components/Element/Header/Header.jsx
  src/components/Element/Input/Input.jsx
  src/components/Element/Input/index.js
  src/pages/Product/components/InputProductImage.jsx
  src/pages/Product/components/ProductForm.jsx
  src/pages/Product/index.js
  src/pages/Product/routes/Product.jsx
  src/pages/Product/styles/Product.scss
  src/routes/index.js
Labels: 🎨 디자인, 🛠️ 기능개발

#47 design & add : 회원가입 및 프로필 설정 페이지
  src/components/Element/Input/Input.jsx
  src/components/Element/Input/Input.scss
  src/components/Element/Input/InputImg.jsx
  src/components/Element/Input/InputImg.scss
  src/components/Element/Input/index.js
  src/components/Element/Post/ButtonLike.jsx
  src/components/Element/Post/Post.jsx
  src/components/Information/Information.jsx
  src/components/Information/index.js
  src/components/InputComponents/InputAcctname.jsx
  src/components/InputComponents/InputEmail.jsx
  src/components/InputComponents/InputIntro.jsx
  src/components/InputComponents/InputPw.jsx
  src/components/InputComponents/InputUsername.jsx
  src/components/InputComponents/index.js
  src/pages/EditProfile/index.js
  src/pages/EditProfile/routes/EditProfile.jsx
  src/pages/EditProfile/style/EditProfile.scss
  src/pages/Home/routes/Home.jsx
  src/pages/SignUp/components/Account.jsx
  src/pages/SignUp/index.js
  src/pages/SignUp/routes/SignUp.jsx
  src/pages/SignUp/style/SignUp.scss
  src/routes/index.js
  src/styles/scss/join_membership.scss
Labels: 🎨 디자인, 🛠️ 기능개발

#38 design & add : 게시글 상세 페이지, 게시글 업로드/수정 페이지
  .eslintrc
  package-lock.json
  package.json
  src/components/Element/Comment/Comment.jsx
  src/components/Element/Post/Post.jsx
  src/components/Element/Post/Post.scss
  src/libs/dummy/index.js
  src/libs/dummy/post.js
  src/pages/Home/components/HomeWithPost.jsx
  src/pages/Home/style/Home.scss
  src/pages/Post/components/Comment.jsx
  src/pages/Post/components/CommentInput.jsx
  src/pages/Post/index.js
  src/pages/Post/routes/PostDetail.jsx
  src/pages/Post/style/Comment.scss
  src/pages/Post/style/CommentInput.scss
  src/pages/Post/style/PostDetail.scss
  src/pages/Posting/components/ImageArea.jsx
  src/pages/Posting/components/ImageItem.jsx
  src/pages/Posting/components/TextArea.jsx
  src/pages/Posting/index.js
  src/pages/Posting/routes/Posting.jsx
  src/pages/Posting/style/ImageItem.scss
  src/pages/Posting/style/Posting.scss
  src/pages/Posting/style/TextArea.scss
  src/pages/Search/routes/Search.jsx
  src/pages/Search/style/Search.scss
  src/routes/index.js
  src/styles/scss/component.scss
  src/styles/scss/post_detail.scss
  src/styles/scss/post_upload.scss
Labels: 🎨 디자인, ♻️ 리팩토링

#51 fix : scss - main wrapper 추가
  src/components/Element/Input/Input.scss
  src/components/Element/Navbar/Navbar.jsx
  src/components/Element/Navbar/Navbar.scss
  src/pages/ChatList/components/ChatListItem.jsx
  src/pages/ChatList/routes/ChatList.jsx
  src/pages/ChatList/styles/ChatList.scss
  src/pages/ChatRoom/routes/ChatRoom.jsx
  src/pages/ChatRoom/styles/ChatBubble.scss
  src/pages/ChatRoom/styles/ChatRoom.scss
  src/pages/EditProfile/routes/EditProfile.jsx
  src/pages/EditProfile/style/EditProfile.scss
  src/pages/Error/Error.jsx
  src/pages/Error/Error.scss
  src/pages/Home/components/HomeWithPost.jsx
  src/pages/Home/components/HomeWithoutPost.jsx
  src/pages/Home/routes/Home.jsx
  src/pages/Home/style/Home.scss
  src/pages/Login/components/LoginForm.jsx
  src/pages/Login/routes/Login.jsx
  src/pages/Login/routes/LoginEmail.jsx
  src/pages/Login/styles/Login.scss
  src/pages/Login/styles/LoginEmail.scss
  src/pages/Post/routes/PostDetail.jsx
  src/pages/Post/style/PostDetail.scss
  src/pages/Posting/routes/Posting.jsx
  src/pages/Posting/style/Posting.scss
  src/pages/Product/routes/Product.jsx
  src/pages/Product/styles/Product.scss
  src/pages/Profile/styles/PostSection.scss
  src/pages/Profile/styles/ProfileSection.scss
  src/pages/SignUp/style/SignUp.scss
  src/pages/Splash/Splash.scss
Labels: scss, ♻️ 리팩토링

#53 add : axios 관련 세팅 추가 (#52)
  src/configs/config.js
  src/libs/axios.js
  src/utils/storage.js
Labels: ⚙️ 개발환경, 🛠️ 기능개발

#56 feat : home 요청 추가, 좋아요 기능 + util
  src/assets/error-image-hc.png
  src/assets/error-image.png
  src/components/Element/Input/InputImg.jsx
  src/components/Element/Post/ButtonLike.jsx
  src/components/Element/Post/Post.jsx
  src/components/Element/User/ProfileImg.jsx
  src/components/Element/User/User.jsx
  src/components/Element/User/UserInfo.jsx
  src/components/Element/User/style/UserInfo.scss
  src/libs/api/axios.js
  src/pages/ChatRoom/routes/ChatRoom.jsx
  src/pages/Home/api/index.js
  src/pages/Home/components/HomeWithPost.jsx
  src/pages/Home/routes/Home.jsx
  src/pages/Product/components/InputProductImage.jsx
  src/pages/Profile/components/ProductSectionElement/ProductItem.jsx
  src/routes/index.js
  src/utils/date.js
  src/utils/imageUrlProcess.js
  src/utils/storage.js
Labels: 🛠️ 기능개발, ♻️ 리팩토링

#54 add : 상품 업로드/수정 페이지 API 연결
  src/pages/Product/api/index.js
  src/pages/Product/components/ProductForm.jsx
  src/pages/Product/routes/Product.jsx
  src/routes/index.js
Labels: 🛠️ 기능개발

#59 add : 프로필 페이지 API 연결 & fix : 링크 수정
  src/components/Element/Navbar/Navbar.jsx
  src/components/Element/User/User.jsx
  src/pages/Profile/api/index.js
  src/pages/Profile/components/PostSectionElement/AlbumView.jsx
  src/pages/Profile/components/ProfileSection.jsx
  src/pages/Profile/components/ProfileSectionElement/ButtonsYourProfile.jsx
  src/pages/Profile/components/ProfileSectionElement/Follwers.jsx
  src/pages/Profile/components/ProfileSectionElement/UserInformation.jsx
  src/pages/Profile/recoils/atoms.js
  src/pages/Profile/routes/UserProfile.jsx
  src/pages/Profile/styles/ProductSection.scss
Labels: 🎨 디자인, 🛠️ 기능개발

#58 Feat : login 기능
  src/components/Element/Input/Input.jsx
  src/components/Element/User/User.jsx
  src/pages/Login/api/index.js
  src/pages/Login/components/LoginForm.jsx
  src/pages/Login/styles/LoginEmail.scss
  src/pages/Splash/Splash.jsx
  src/routes/index.js
  src/utils/storage.js
Labels: 🎨 디자인, 🛠️ 기능개발

#61 Feat : follow page (follower, following)
  src/components/Element/User/style/UserInfo.scss
  src/pages/Follow/api/index.js
  src/pages/Follow/components/FollowButton.jsx
  src/pages/Follow/components/FollowItem.jsx
  src/pages/Follow/components/FollowList.jsx
  src/pages/Follow/routes/Follow.jsx
  src/pages/Profile/components/ProfileSectionElement/Follwers.jsx
  src/pages/Profile/components/ProfileSectionElement/UserInformation.jsx
Labels: 🛠️ 기능개발

#65 Feat : posting
  src/components/Element/Post/Post.jsx
  src/libs/constant/regex.js
  src/pages/Posting/api/index.js
  src/pages/Posting/components/ImageArea.jsx
  src/pages/Posting/components/ImageItem.jsx
  src/pages/Posting/routes/Posting.jsx
  src/pages/Profile/components/PostSectionElement/AlbumView.jsx
Labels: 🛠️ 기능개발
